### ISSUE TITLE
db.php

### ISSUE THREAD

**Issue by donj51** [ljosberinn/Solar-Panel-API#1]
Do you have db.php?

**Comment by ljosberinn** [comment]
Wow, sorry I didn't see your issue and never actually expected anyone to use this repo :)

the 'db.php' only contains:

```php
$host = 'YOUR_HOST';
$user = 'YOUR_USERNAME';
$pw = 'PASSWORD';
$db = 'DATABASE_NAME';
```

that said, it's not supposed to be run on the open internet, else this is a potential security risk.

**Comment by ljosberinn** [comment]
Also, you'll need to replace the station ID in the fetcher.php:

```php
  $url = "https://monitoringapi.solaredge.com/site/319863/powerDetails.json?startTime=" .$year. "-" .$month. "-1%200:0:0&endTime=" .$year. "-" .$month. "-" .$days_in_month. "%200:0:0&api_key=" .$key;
```

319863 is the number, somewhere in their API endpoints youll find yours
